apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: migration
          image: ghcr.io/otomad-database/api-postgres-migration:main
          env:
            # Postgres
            - name: POSTGRES_HOST
              # value: postgres
              valueFrom: # TODO: 本当にこれしかないのか？
                configMapKeyRef:
                  name: api-configmap
                  key: postgres_host
            - name: POSTGRES_PORT
              # value: "5432"
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: postgres_port
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PRISMA_DATABASE_URL
              value: postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DATABASE)
      containers:
        - name: api
          image: ghcr.io/otomad-database/api:main
          imagePullPolicy: Always
          ports:
            - name: api-http
              containerPort: 4000
          resources:
            limits:
              cpu: "4"
              memory: "512Mi"
          env:
            - name: PORT
              value: "4000"
            - name: HOST
              value: "0.0.0.0"
            # Postgres
            - name: POSTGRES_HOST
              valueFrom: # TODO: 本当にこれしかないのか？
                configMapKeyRef:
                  name: api-configmap
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: postgres_port
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PRISMA_DATABASE_URL
              value: postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DATABASE)
            # Neo4j
            - name: NEO4J_HOST
              valueFrom: # TODO: 本当にこれしかないのか？
                configMapKeyRef:
                  name: api-configmap
                  key: neo4j_host
            - name: NEO4J_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: neo4j_port
            - name: NEO4J_URL
              value: bolt://$(NEO4J_HOST):$(NEO4J_PORT)
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: username
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: password
