apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
commonLabels:
  env: production
bases:
  - ../../base
resources:
  - ./api-service.yml
  - ./neo4j-auth.yml
  - ./postgres-auth.yml
