apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otomadb-neo4j-auth
  namespace: default
spec:
  encryptedData:
    password: AgBpvc80EjzySWccfDsvrpIZyUjwDMAe+pII7+GN5dMY2vbRIehBvWuXHC34D2vBOeqsUMdgPTE8hC2ABXJEaDDUHlaZ/t5XMFxiWk0LkwVTABicWXVdOxRSstZ+nb7DVLVhQMWD/tFG3els+GDakH4HIYpYuqjGk3I9Qsb+dSmnN6qxpidBMF1cnhvk/OK7IrJ01DIsptvXV+VXrFp+S0/afSAYRsjdpNhBVWZIfv0T2R352rh7E9CYIQevMK3j5uxkDo4QIX13g7ds1e4DQ33Al/9Jac7DdcIErah1X7RAJlloSnGwPkM/rgileL+raxaHmnoy3b4N7TB4b718DwZQgn9tNmMk/ACLZCtWOo6rGUSuZC+pIbdQsNUtgWWgxXqaU6xjoON4HrM1M2WAPrdkOom1YWFqgaICTzZf+jA/TKDkb9Kryd8a8Z5apCchW9cFvk8SnzSgh+nyJAK/5wLy1EVywYz2SFEq6SYprDvKCVMsVEYZner8LH2fo+g9WrqFtD4R/jd1+2BccRHtP6GMirxVkGwu+HbXoE/q/us0DjjWH/oMfb/3PElqU0H5m2D88KYoUCWxtvEMTALT/Z54ny0TGwDj2/6CsTYsGhMElXI+CvE/N4/ZAT1B2H9+ETByPXwFOU6MS2Yo9EPuUFeyKt21dWrXVZ2HB1PSRDfovAvmkXfkujlJuLG9GZbocw9+YtrHZ2NG9/t5IXfBgqdKIwuIvMRPAm9T9pNbqfXTVg==
    username: AgAY2Wyb0IxQf6sYDs3LTCha7xXfmy+yACzf9Qtf5i2Fv3drgr5NgQAxY+WshCM66R+sPW5dW7l5avEPCltiEhy5zK3lrPS0AKrlUdAQ0DJ7aztflxAho/nlG4EdQRV4xcG62HDbolZ6U2/a54AFKx26Xtdb90SHqy1zdIbF9NPi+tZYEecqyxai4yqMLIBeEmBtt6cWPJ16BR0/vbNoXwFkEYfvO7pGB8tLV6uQ0XCxpIKTEyjozCaus5u9bdByVFQtVSPuLGQDHXAxsQ9+NUMZWi4XHCXTSBzLsvIi6iGmLDo/zsIJIrmSmfeKcaxXZHt30GfppMw3FNQeMtpzAdVOtxbvkl8sWyzMYyQm0SsieAPcWk2/3rIt5DzBFkxelYFH77bMYsFeaRxSjxz9jwiassx8BDe8XfTkyoebKJizGnthwCOMuoAAPXC/IiANQS8AY1rnDnshD1DCWx4slKmPNKhpbPuO6RxPOropb7jaCoE0dbPO/fLhBGeLyxFQuHeWitIHDnuOGPZAPw52++kEg/QjoQgCquWgeTgUGRLG+jP4qUaurFK++SO/ErIXRv+ouNbMVUnejbUYdkJhyOI0g7OdeV7NHPmOC4kg6Z0ua/ujCHI6unjzP0cJxLLd7GV2mYHBLfXtASJtW/hdTqTY5JdowL1IRHc4aHp+fyqXCnqnsyzMRY7XD9CPi0hasaBrzwy0Zg==
  template:
    metadata:
      creationTimestamp: null
      name: otomadb-neo4j-auth
      namespace: default
    type: Opaque
