apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: otomadb
resources:
  # - ./namespace.yaml
  # api
  - ./api/deployment.yaml
  # neo4j
  - ./neo4j/service.yaml
  - ./neo4j/statefulset.yaml
  # postgres
  - ./postgres/service.yaml
  - ./postgres/statefulset.yaml
configurations:
  - ./kustomize/sealed-secret-config.yaml
configMapGenerator:
  - name: postgres-configmap
    envs:
      - ./postgres/config.env
secretGenerator:
  - name: postgres-secret
    type: Opaque
    options:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
  - name: neo4j-secret
    type: Opaque
    options:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
# generatorOptions:
#   annotations:
#     sealedsecrets.bitnami.com/managed: "true"
#     sealedsecrets.bitnami.com/namespace-wide: "true"
