apiVersion: v1
kind: Service
metadata:
  name: otomadb-postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app: otomadb-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otomadb-postgres
spec:
  serviceName: otomadb-postgres
  selector:
    matchLabels:
      app: otomadb-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: otomadb-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: otomadb-postgres-config
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: otomadb-postgres-auth
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otomadb-postgres-auth
                  key: password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgres/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
