apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    password: AgAdLefbRM7PxbmdnbBvclMMpCTCBEfVByiLIFDxEJEOAYWtRuN/chjGBftPKdwDIYkrsR+ek38Y/GkLVLPuJrZRFdXyOE3iq8MxMjWbJtshanNd+bJeuDqx9kNRcXUXe4fbcNJt476XFYn+sfrn3UlTVvvpsF+SVdE2S7e3f4CSLZrKimj4VrYHYJMwHPsUMllwtlCYoHQXmdzUd6tbSzMuRKL7SaMVPzUqGswLIYOONlmqnbLVUXxac9qauEkV5tx5Kfuc4f/DYmKGNClQJIMRQqBH4mMmRPyIBVQMWVbmGOa59dMDT6B5qcAkcEok0pmWni60+FfiyzQtVvqvOQuXlcjFfCF0aVNdJ57ZPRQrlKz3mHi6B+mDYG3OieqrGbjnE2uzAzBDmQ0mH7xN8JGDKELcfufX1GmEWWAxOEQg0nrFS2QbSJTCeC+2AVAB1WbeSWfMrPeYiHZnKQEzfyUUKqBcucBVWVcvidGbHaP+sh5/0euyjfrk/pZgfgrDMcHRjRF3z3ZjK8ZMzUuI0J69JXbjd81vfW332ZutMilDokFKmpLgJw5plURiYE/eFnCwjfjyNI6Pf7mrPEDwZ6EYRSme6+d+vruCvaRwpmHziM4ZUthI+OJagoicfC2apz4VlJmvpSGiJsd2OY6G9lGlXijFphZMBtmH0NbrVnh7aMII+fgc+raHtySGMNU7TMeHDB4MrECQXUHVZ1OEp677K0rNjbFPRqbS+Lqn25ii/A==
    username: AgCRdIdQpYSPwDgajmNWGiJu1YjvE8igaYMhrEHFarSqyn75CYwYKzQn/Yw6HAUNtjX/IBi7KrctFCVmgZ69Vy69Ig6+3MyNgvKjVzPO3j1dMWW0uq+OJaQ5VLuWK6kDJ6EsdEfa4Fe5YwxF6F76nGGF2bSOXno7qfMRG9/YS+Eo57x5wwOO97Sl5A2lKMMhySsEruZla9UbsuR3nIObL1xFfslivPmcJUhlzAzQ8CmP/SAmTuCByNHVNxEgAp4SDj8u5y0F+Nph3D8es3Ks2dkddgKKTMxSduxFiraSNPYR65tcuucCfEhultA4QZTFQD/89nYqbWEK5Tl8IdWv43JfeDK4Gqig9h98vEEBIZbl5iG4I3osZ5oaiAfNdp/X456rJrbsEtOVvms9b75zVK8HrF1byjQVGuxaQSVen8u9dcZ6oeaDUUMD4EaiVl2VGViEsVOpnbtWEWai7alMDu5X3vFanlk1Melp4Q3XfehCf/N5e6q6pqiVkIii+yB5cxJORqKHqZ8QXw4HVebEw9zvfBYDE4M45B/ME2KBtfP7qfeg4mlrtalxhuJX610wwIJZE0SreZdKjMj84m0fvMKDWIx0tPv2JRFQF7sGnmn8onY6C6weDWuV2OdWuHn1tTdNy1dF4ni3mLZXaaqTK/k4HReyxzzMgvBiWCHI78I+ov6ytWS0+blI730oQIDfln2uTYDF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque
