apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod-otomadb
commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
configMapGenerator:
- name: api-configmap
  behavior: merge
  literals:
  - enable_samesite_none="false"
  - enable_graphiql="false"
images:
- name: api
  newName: ghcr.io/otomad-database/api
  digest: sha256:60b19376d3194c7ba797633765cb5e5a1764bab2b41c596e2278d143bb9350b9
- name: api-postgres-migration
  newName: ghcr.io/otomad-database/api-postgres-migration
  newTag: c1b7d8ebae139b12c0965eb3686bf8ff78271b8d
