apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
bases:
  - ../../base
resources:
  - ./ingress.yaml
  # Postgres
  - ./postgres/secret.yaml
  # Neo4j
  - ./neo4j/secret.yaml
