apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod-otomadb
commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
generators:
  - ./ksops-secret-generator.yaml
bases:
  - ../../base
resources:
  - ./ingress.yaml
