apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod-otomadb
commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
configMapGenerator:
- name: api-configmap
  behavior: merge
  literals:
  - enable_samesite_none="false"
  - enable_graphiql="false"
images:
- name: api
  newName: ghcr.io/otomad-database/api
  digest: sha256:366cea2c509ee6672968bd8d2c93d0349b9624bef6bc8d4239d2726c98ad3890
- name: api-postgres-migration
  newName: ghcr.io/otomad-database/api-postgres-migration
  newTag: c1b7d8ebae139b12c0965eb3686bf8ff78271b8d
