apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod-otomadb
commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
images:
- name: api
  newName: ghcr.io/otomad-database/api
  digest: sha256:56be5c7b97a1173cac0c50cf45274dd2f378e3c250e26fb37f7cd61c767a400a
- name: api-postgres-migration
  newName: ghcr.io/otomad-database/api-postgres-migration
  digest: sha256:977983bc20d162bee82df3f07210aceb75bc51a876feab681be93211448203a4
