apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod-otomadb
commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
configMapGenerator:
- name: api-configmap
  behavior: merge
  literals:
  - enable_samesite_none="false"
  - enable_graphiql="false"
images:
- name: api
  newName: ghcr.io/otomad-database/api
  digest: sha256:61e8f777c11facba332369034f5238f4cd7a4abf3d14cec2137750b9d3bd81ad
- name: api-postgres-migration
  newName: ghcr.io/otomad-database/api-postgres-migration
  newTag: 6914be31e0d4d7e10eb6a931cab05e3f3d9345b9
