apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  PRISMA_DATABASE_URL: ENC[AES256_GCM,data:eVNp9iQaKWZuCmfYh8N5uBSxuCGZ9PUk46s+R5kwGWqMzm4EBHZ26hRMs8M0tR7BlJoQjxfK,iv:48iX2gYs/MVdhxHhdYmf1bZbx4LTZe/lbN2OasdYdPE=,tag:47poBzY6760DriB28mxjwg==,type:str]
  NEO4J_URL: ENC[AES256_GCM,data:UlDX6YYpzAIQK+KETHvLF1o=,iv:Bsq1IA8p7YU+jCBQCFRqkjXXduxQsIFgpNDdxzAR3jU=,tag:ENWFo0CFpx61LAsHonnxHA==,type:str]
  NEO4J_USERNAME: ENC[AES256_GCM,data:zY4KM/Y=,iv:C1ETn4kp6zTimSTAlnLdE358PdMW7qQGFNC1dVDE3Bw=,tag:1HS91TfNfsRwUF7ySBmRJA==,type:str]
  NEO4J_PASSWORD: ENC[AES256_GCM,data:vaP/kPBD/QkGqba7+8U=,iv:q1omg1fXW5fuhdhhQl7On1kXWNSqHUtXp/xGMuxEAFs=,tag:Hr1S/btxLyO4wnoG0eZ6pw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-02-05T20:41:38Z"
  mac: ENC[AES256_GCM,data:0HWLwBJP78bKTA6uAfZBPdlJXqgiETsIwzOkB+TKuDAxr7Zefd42HcuBzVQp2N+cvXdMvtmyB3GtozeuS3WYUD86KoPzen6/eIIAVoYFoLVrZD1uuumn5TKJZW1x+zmDrxJa+ffZt9HIUGzs4bzl32FZYKKqbfaSYKxBS36TReA=,iv:z45W+XHaw69IQF1XN9bm+Lra4fryjdUnsHUdx/qqeaI=,tag:h+cIGxAnaVE8NGaMJx70Qw==,type:str]
  pgp:
    - created_at: "2023-02-05T20:41:37Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAyadMEQU/CnhAQ/8DzBQ+s6BmASX5nc2VUrhLPfB7dXOGVA6GAr5pQeq3YnO
        v0RK7x6C0lO+d20pq1TU4lJm5n1q0TedB7Hq6RTiDWjyBHiMdeL/fjdk2Pd6Agnb
        9MLPE3XBES+eGrTsRFZ1G/eDcmv2HRqzzsJGH3XS/uFLMK+AN+7DcG7kywW/cP7e
        7QSFbVJ9/w3uHRsEoWFlpwFgXJk2f0BIZmlFzi12jofESL097o/hT2vsRJPkkJq5
        HfWY8qJTxGxeT69fAr/SRQhp8cQcZj3POSSx7aHDbyQZFBHdcgB2XzP+qze/mgau
        Wh015ny8CrC+TNvaI5lfjEYPBoKq++kaqpKtUM5Xo7NbamjO0IrI+1JFQxTJuEuo
        d2Pc0V2KBHkcl0VB07tXaRPKTIhLFNT9/QNFWaMX/7IxCwYIz94ubTs7jM2Sn38W
        MdlS7jgnggKAzj2eHjlP/+iPjFqlYDO497RwevJ/Ldc/Ri4dS+oiFjDcuDHXd6hK
        BtQZoFEpz6ZS8ZI2PpN0S45K9ODPNzUyZeUOizNdKpztrvFclJcKp2RACrBqhe57
        Epq5/kkRsaujZti2PQVu53/FQ/KBxgC0llGTGvKDpyIU/C31+bqFUezDajsTa0xo
        LIWYfYOBBZWI0OAL3Vfy1x3YeyD1gBFRbZdVla99EgJsa6Pm6WUzmf+/JJYkBpPU
        ZgEJAhBEkC46ymbGdej8VYPiRXwr4OY1q+uMGv+m3JRS6a8w7dVORhbuD93DVJyF
        Ob1+gGFqrhObLJtrTfRjsTJtfb0zX4DXE60E61depQdqLlWi7WQcopjeue+ikwdP
        swkCU2D2wg==
        =PjFi
        -----END PGP MESSAGE-----
      fp: 4052669590974A212F67DBE4282792C188CFBA1F
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
