apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otomadb-api
  annotations:
    argocd-image-updater.argoproj.io/argocd.force-update: true
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/otomad-database/api:latest,
      api-postgres-migration=ghcr.io/otomad-database/api-postgres-migration:latest
    # api
    argocd-image-updater.argoproj.io/api.update-strategy: digest
    argocd-image-updater.argoproj.io/api.kustomize.image-name: api
    # api-postgres-migration
    argocd-image-updater.argoproj.io/api-postgres-migration.update-strategy: digest
    argocd-image-updater.argoproj.io/api-postgres-migration.kustomize.image-name: api-postgres-migration
spec:
  project: prev-otomadb
  source:
    repoURL: git@github.com:otomad-database/k8s-manifests.git
    targetRevision: prev
    path: api/overlays/prev
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prev-otomadb
