apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: otomadb-postgres
spec:
  project: prev-otomadb
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "12.1.14"
    helm:
      releaseName: postgresql
      parameters:
        - name: "auth.database"
          value: otomadb
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prev-otomadb
