---
apiVersion: v1
kind: Service
metadata:
  name: otomadb-api-service
spec:
  type: NodePort
  selector:
    app: otomadb-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otomadb-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otomadb-api
  template:
    metadata:
      labels:
        app: otomadb-api
    spec:
      initContainers:
        - name: migrations
          image: ghcr.io/otomad-database/otomad-database/api-migration
          env:
            - name: DATABASE_URL
              value: postgres://user:pass@otomadb-postgres:5432/otomadb
      containers:
        - name: api
          image: ghcr.io/otomad-database/otomad-database/api
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: HOST
              value: "0.0.0.0"
            - name: DATABASE_URL
              value: postgres://user:pass@otomadb-postgres:5432/otomadb
            - name: NEO4J_URL
              value: bolt://otomadb-neo4j:7687
            - name: NEO4J_USERNAME
              value: neo4j
            - name: NEO4J_PASSWORD
              value: password
