apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otomadb-postgres-auth
  namespace: default
spec:
  encryptedData:
    password: AgAnFVqFnsYaFRdyYEV4ARwz00GO/iLdcU4iPROYzkZyS8vCRlCtRaGoqmHEje79EmuLYXdy6QPK3sdWiMww+CK7o2M0K+u9j6Sh+Z11OyW+2Hgc6cyPK3TN8oiPUemcyr/EOcfjliTai/o24Cmp0W0cYLDLc8I4XIhTrvRUNxXIRNKKAXD+hYuq9wrz/9clKyo0ZYHjFHfAHEEgJ+Z4U7/0vLoDOo9w2diScZ/aH1eRsWG8msZHQbMFeSotXA8ENxQyNOfSm9qC8dwGdtl2Mags6NXvRnS0GXr5iPU9WGU38ecFTkgyW+sxe3l8JSp7CIc2iUZLckM5yKfh6vNxfcYwPjYFCizfcekIEyA6hUjr907sQszr9f+oCU6kFJCllyk0KXIw5Emm4jta3cybj+l1JpkAgk6YQtwM5jK/T6Y8j9x7MNom/0OsBoJ/iesw6x0yS6lf4iltuELJTaxW0V7HouTAZWkANt6ie0dYGI+AKqZgz4NvPRBccA9iOBOuaOxdPmtTsQKCOv/r60nCrOBBLXnQXMYxWYMa58vaGITslJL73GDUsQfpl/iCJbQTtYVZpllJuh1vzz9IS9cTau4BGNWq88aMssHk22D5nhyh7UQVOED9d9BO91dd6eYDeH/wyRl5ZmccRZOURYB3J8y1gE4iA5m+3OqMac+d7Qy58A8nAoybX0dG4aeaZ6+wtDCacCiPhiWcHv8CJRlbOVhvbYIujLXVVzlcGwOhIKy+rw==
    username: AgB/RR+sXUS7PuCbhDB4G6lug5MaXRManAOVcqgBKUD7uAgQJ8sU4h9dR2kqz4sOAmF/Z0LFo9axB0N1JU8Bhbi5vb6D3hScT6mO+2T+nqP/Gxv/zMt/OMZUBQZXtpAUnHiVe2JRYmeXac8P/3jcp0Xr3DnsCXvgX2NIRaKWjzcMuLbhIE6q3oeqHrwN3AKI3Qz3pQbzYYW7Fv0EoudScO5f4zD21X3Ep17clSaWABDVZsRqdJGhXGy2WvxZB/r8saIFGIjay4P34rrUENZPZvvXyMRaZs9Z0OG6Av51TO47PeMts8EAj5HbVBSXQh//7NXzaLe+4ImiFXN8AbvSOqb/m5r/APIoX0pKT8VT38Xxiww5r4Jp/0FQ/qTPYHBvaLrGztf4VQdR0facxr1IeKrDigeWXsf+uhKp7Vjc8uNi5X21tECtNczbO8DLrjkU49w/jJGphWUdrFVuMJQCt/GPvZczRn02CqF06P8WvfryNOr1u3r7MXk9iK0gOJuvw2WQ5pcwR2TozTW3OCq3oJc5pJtyWda0fXd9ehctC5kuxVO/7WFQVPrCQvbX40HJq4JFdslAfGFZxXnjiWFeP8H0qNyozqsMHwQLh2oI7nfutAGQSj70iTqmY8kVNJJVHFtzDAwiBTsDvhsPqDVMmYVxob2bwXXs2qKm3JCWqL7h1/9YIFFfILZ/uQtfz6FONmve/2Ws
  template:
    metadata:
      creationTimestamp: null
      name: otomadb-postgres-auth
      namespace: default
    type: Opaque
