apiVersion: v1
kind: Service
metadata:
  name: otomadb-postgres
  labels:
    app: otomadb-postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: otomadb-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otomadb-postgres
  labels:
    app: otomadb-postgres
spec:
  serviceName: otomadb-postgres
  selector:
    matchLabels:
      app: otomadb-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: otomadb-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: otomadb
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgres/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
