apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: migration
          image: ghcr.io/otomad-database/api-postgres-migration:main@sha256:2318ee4beccace75eb73b0ee35c57e94373218451ae69a883439f9e50bbaf7ae
          env:
            - name: PRISMA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: PRISMA_DATABASE_URL
      containers:
        - name: api
          image: ghcr.io/otomad-database/api:main@sha256:6a6f75f176d8600d009ee5654cfaea681e97b1232c584abde351e8813371696c
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "4"
              memory: "512Mi"
          env:
            # Postgres
            - name: PRISMA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: PRISMA_DATABASE_URL
            # Neo4j
            - name: NEO4J_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NEO4J_URL
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NEO4J_USERNAME
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NEO4J_PASSWORD
