apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: migration
          image: ghcr.io/otomad-database/api-postgres-migration:main@sha256:ac843467d5da3904275061eb8b49da5d9e107c0bf2b9da5adda1c1a3b222664c
          imagePullPolicy: IfNotPresent
          env:
            - name: PRISMA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: PRISMA_DATABASE_URL
      containers:
        - name: api
          image: ghcr.io/otomad-database/api:main@sha256:7dbdf92ac13ab7bfd990e178422088292c04ecbcf6d3ff5149a8e1b3096a0681
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "4"
              memory: "512Mi"
          env:
            # Postgres
            - name: PRISMA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: PRISMA_DATABASE_URL
            # Neo4j
            - name: NEO4J_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NEO4J_URL
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NEO4J_USERNAME
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NEO4J_PASSWORD
