apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - ./.kustomize/sealed-secret-config.yaml
resources:
  - ./deployment.yaml
  - ./service.yaml
  # postgres
  - ./postgres/service.yaml
  - ./postgres/statefulset.yaml
configMapGenerator:
  - name: postgres-config
    envs:
      - ./postgres/config.env
secretGenerator:
  - name: postgres-secret
    type: Opaque
    options:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
