apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - ./.kustomize/sealed-secret-config.yaml
resources:
  - ./deployment.yaml
  - ./service.yaml
# configMapGenerator:
#   - name: postgres-config
#     envs:
#       - ./postgres/config.env
# secretGenerator:
#   - name: api-secret
#     type: Opaque
