apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otomadb-postgres-auth
  namespace: default
spec:
  encryptedData:
    password: AgC00uQ3S2qXEVKjPigcw09yMyllDvTpylb04DL+OtSh3MIv8wbRmKTKKCCFjheEa3yTtXQdEFA1ldBkp7a7y9LtqjMQ7brpvmDPJ3uc9oDNQq/4h1WW5x6J5A5163vAli+ZPPzZRyKY1nclwNfmteil+VQxyw5cJRCnM29AE8FCx2j2KpbfJ85Wm+EUItQgmIX9aSJeRnlcjjhFfg7iLwR2ohcA//DK8Nblwh54904mkYkSoTxQEqVNV0znSrPGh+ZhHX3zKKi50m6ixF/MfFYUX1K19RhhQFANEH0s1eaI/aw7Bml1lJ6clwpCDw7gmlHHcGDy5XR7qvBfd6qxLM5rJXRmAYdelf89LvS6m9/uwAi1DXxDWEql9O+F6bcrcGkyosh1SM45hs0AADVAXUJt/fHTQtiyyHmxxtZUTbhVBfDeTQbqynSBjnwKgHBS2WlPfbCflflFxP8zgsiiqA+ydH8GVWXBJyEo7kRAeRfhXCvV/p1Wz97NImS1GoIqSVyGDupHkPJ+pjq+nmU/h1RHhjV+dPCLvIeLeOFq3kRY5mTCZ6lUr4jE2/PJB5QpEsUcm/Ui/nJ5uC3FJmffF1zhYiNLjX30xU0vpxkxjIDULQDos9oonxy60ogsik5AV0tBeB5DLiE8OpYKBMVGYE5TA41GLIxIqzp07PaOUmpSsu1iNkZLMUysRRKFCcjPOyxuDvQGRGmDtSrFORb7wR4flsxX7Vl0w1CJE3hce7raIw==
    username: AgAX9BVSksWLWYmFHZDMx4aIlm6eXvgXZcUVQF+arv2K3vEW1N1fhVnppd0hK1Aei1N42BPwZLiU4R9YL1bSIl0623GUz7SFXPn2NIB9khXxVNavHq3EEaC8KVdx6YhOLa+2avM9/saLv0fNzvN34J/QZLudIlt3Qe1zaqJ9mHY+UTzkIZCK17JzpemOZzxYu/h0qCZ12eSefQpf/C895ZTyZgn40jzyJ/i3MlST+GmjbLBvfdgSHrAVpzvPJy88NCZjNT+9QDZsS8qbYPmubnXg2T1yzLS95WWKSfqRYVLCanxZGahj783qrGyMvL/8N6ZEkFtSheycSA+lYAU2X+7cUz8FbpxfEeX5Y/qaDF0fLn+7UCTpwKEVgo8g3X9fYfNCBnb5+3O/Bbq2lThhvbO0Wf0yH2pgI7wdD1+7gPuPGShCfm4JNNLt58rWRvcDijrRDGHTD0eLA161y+p/OwBYZZLlv0xW7hD8JGQl27I3tC57mHGWlVdOzMVUV16I/hvj68pvztX2ncjmXhcdGjZM9ReaskTl1xbffineNlLb8XiLbeRO4iLZz0ZCq3U/HwJtsaOiNVPM9QaNLu7IY7OhGxHr51y0opVRa64rlZrdSZzGMiA+WjZVm2AI2NikaIx1hyXmFqrvLKbGKuuEsRETG7GrrmHl2KimXngVhSRqGJRWssfhU16TAy9duj0NLlEUAjUY
  template:
    metadata:
      creationTimestamp: null
      name: otomadb-postgres-auth
      namespace: default
    type: Opaque
