apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prev-
namespace: prev-otomadb
commonLabels:
  app.kubernetes.io/env: prev
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
configMapGenerator:
- name: api-configmap
  behavior: merge
  literals:
  - enable_samesite_none="true"
  - enable_graphiql="true"
images:
- name: api
  newName: ghcr.io/otomad-database/api
  digest: sha256:d7808f894e54e7f4eacaa93ba12f8a203a7be944789a46a8575ae3c282f24bb0
- name: api-postgres-migration
  newName: ghcr.io/otomad-database/api-postgres-migration
  newTag: 6914be31e0d4d7e10eb6a931cab05e3f3d9345b9
