apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prev-
namespace: prev-otomadb
commonLabels:
  app.kubernetes.io/env: prev
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
configMapGenerator:
- name: api-configmap
  behavior: merge
  literals:
  - enable_samesite_none="true"
  - enable_graphiql="true"
images:
- name: api
  newName: ghcr.io/otomad-database/api
  digest: sha256:c0e6b4136dd54d3b7ffb6c3cc790344ac2a10548a4407ae0da544e92fc2e7e0a
- name: api-postgres-migration
  newName: ghcr.io/otomad-database/api-postgres-migration
  newTag: c1b7d8ebae139b12c0965eb3686bf8ff78271b8d
