apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prev-
namespace: prev-otomadb
commonLabels:
  app.kubernetes.io/env: prev
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
configMapGenerator:
- name: api-configmap
  behavior: merge
  literals:
  - enable_samesite_none="true"
  - enable_graphiql="true"
images:
- name: api
  newName: ghcr.io/otomad-database/api
  digest: sha256:05cc2c5e985032f8d41de9f64aaa511b30b8729d508b31336afbe763bc236cd4
- name: api-postgres-migration
  newName: ghcr.io/otomad-database/api-postgres-migration
  newTag: c1b7d8ebae139b12c0965eb3686bf8ff78271b8d
