apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    password: AgCdpYeSh9OlTRl/qYmJPVZZUj+KQH2IytIdGNWtaeC3lWFDyKu9PxqxzRzFWk5erfr+l93O1W5lakxJE20RRzw29ukCFhvN6YqGA+HW8cpIzH/aHTEs78u893X41OCc1cj9SK4i6lYxr1htmkPM8Lj855g06NsQhJ4tRlHWJ/kOPOtVPKQ/ZhMBz0Bx+r/chzR0MapA6/ZyFRF9VjlsLiML5XwybVboAVlG+00OnNjOXUVsh+KzrJKIKc+29GvmI+kd2oytjIaoFZmfCsXY3olqP32zZdvTB5RL2mSfPY59nkvJp9YAS9cNHWs/HHX6mQN/qg0cfnV2JhwmV+ViS0eBaXp3u16D5DrPc/JSzzOb7TGLU2wHCN9TESCbg53AfbdxMGzeU7+2oHxBuryDxwZgBu4roMVuK8eyWXZ2DfdrWxa1/2X6tZ/ise/1sk7iImfBpW5jqOzt5KPsWOEta+/UAC7Y4C64/iAF+Bae75BH1otf6y0xtFj0VB0V3NAUHsrcwt8bAH+2DuqWQYvqYXv0jSqbOBjIvJJho/bZ6QUHewEDGavDm+1f/Y/+/RL1BFWhkFPct0Sd3FZeXrM5qouAST2yUJ+iOz4e7iKWCf1TJ+lwg5O9+grScnsngOpP5W/OqAfLvj7A2dWYFGKYJYOrtsT9B/r4xYtNTu0F3ShD+l/EZ5TS2UjAo5BF2ie2WwH2XFRoBzm46Rbie/4pFZyk1CjFr/PlzJpWRjYggMGGpA==
    username: AgAlceiA9nAzj3xjlnhUev8PT43zNQ/aa4OpiWQy0PBlLDLt99AsXtrKzn1AtEiKaHcvw7+RDllURLYHVsz/2n8PxCJgvatzcRgLKiVFwryR3rMpsPTqgaVR47Ov0rS5JoX+OFOcKEXX8BjH+3eCdnWbCVDv+gEMfkX8FPFsRDWYfyMF5oO/zreRDLX/ZoiAMfmUZqDIFB8vm6MdvLvS77pxp8L+kGLZQKvd+d7eSyWdFem0fTGeyg0iYkiED2gEq49zGZtAQrQgK+xoqn9lNEh4Rc/tYj6A8OHf+nllX4bvI6GNjCgkam2VoRO3p7bBDcD6kuwWZfxgS/mpJCHW5JZUTJQwjeO01c0L42P8QRYOBAg20pO0QDBWHiN0hhlYfKyZUaz1Psu5fb9v13zJPPjO9muzGVsd1qOGAbozulQywTkkjtfVMZP+HRqn+R7UQlhXVIbDfp0wMDJ2bXe8Burl7MbHqVk4Jh8D7cF88H+toTHEbyIF++HZV2Smjke/H8GFNVLrBE5Smj/S7+yIuWCJmmyTIsIPsQNLBOwXkCy4NcVDFR4JO4YSuujZt3HdiSm3sKVlt2d5dp0d0ykLkReSS0mf1r3Tom20e3A2ICFlviHQSt0O2lanjo3tufGLQoTZJl9ad6z43T0YI8osxLR08IYWocLnYafcaFqkTayi/u6ius8nbxx6eQi+FsOHsX9g75Nm
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-secret
    type: Opaque
