apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    password: AgCBgiXDWhYmANcrkm5p7nHaUc2yt2QNSOwwIty5/PkiQVaRnmw6z+KyqOsWvuiIwc6rzEa1ld/vHL6uh1RQjifiPQg6P90sNeADGkZFQyIK2mZPuohgAsUNHVWMxf/IKvlQ2QSPWPHvRHON+MeCZRWFvqR1B3WPCjCdYrP+fmaCQ08ZX55jqRg44RMC4Dq/Kvz6mGCbxJsIvBE8g7v4ZQ+ppGWN/oLd8SyLMSj6qzmW1WGyjuZzKnfwXsQ58f0/ajp9DCQsMHVdP0QiqRzVToNqJlckubhoT/GIwE/Ez7QTEDfMYf7popHZr/19vMRSWFIMYh580QirlwMc+GxOvVEz2rzIbe4PbWv+f4rYJOAIdTIMVaGLSxICo7R+rYH4huSYb71J6WHzbqqoV9/4HBZt47Ezgn+Qz+C6+0qmy657x3ZhzHRf89Rvk/FMXfkBwlWXasarj2mb/n16eD9P+bpPPouIQ0Hu+P0sM5No83p5cP60XAzzai56gQPCigWBjP/07Hu74lxxKM72qTQIR6nIkuZ4gZ+urdIPC5mXOUfiJx81mqttDscbv1YSKghbCRPeIx3D2daYH4o4JMycfqph07rYBLs8U61K9LhCfqOio0VkOemVm5L0RTYGw5qgC8bab/pH5XjLPA+7WZTXsfoMNm0UkC++HXNHjto0IjpL43PK40RYXThAqQEj7e0eozTd8Hhg1xYp/uyomvMQxCZOalbjZJ3LhOL62A4k89ysiA==
    username: AgBa5GWFoCgtJc8/jf8ekv0sBV/r/RjPVzXhyIc+FkCZFXqXc1nMLPYs4rtx7guvVBvxqKAOjcli6w/Atrvc4QXePTTUwJ8jykeZEZwI4KzgFFzAW1yuYYF1JhLhmb4XOgcScDLN55f2lzmmTpG4v24IgNlfX7RcWnSbUBppj12PEuG/5nT9hGsfE9GRS17Zk8E1v+eBRwspBSfVVeYg9S+1ebKxC4ZnZjP2rB+mp8g6SHhqJxgi5mISFvPO4Oxlc1Sw48m4qtLLlVPIyIDjAWlirIwXt3wN/bgGWajrl9nuCtGkD/BV55ZCutZEX7MgQC3lCWUe1ll39XuxUnlaZREK7R3bw7nl74BC8+ERbD+lC4ThcpWpO6fN9Loh0MUImWC+417fIHXt2kZDwcUJJM0awg1FryhDgbzCxpM49q3BA52CJWIRY7yCp6Af4BNC/c8vKaxQOthEFgJ2bq6r9G7DCdk9aETJdYlVLh89lBYNPFAs4D9bBeHpARt4HXh6qNAKEMGfdgX8UBF9E6wPNV1lg18qXhMot4JoXQbAP3n1ewQOxx+EG/WEbd6CtZo8thTLIZfbNXV4b1f/v9PRVy0L3dQugimFwJdZdPwSjub6+SMkWWGSJFKNRx/rcS/AiIPZhS7L2jZdGKnuEP8ulmmbTSfsoO4B4800thlkZzykw7c2x65xdghO8AIsWflKD1r0VUaH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgres-secret
    type: Opaque
