apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    password: AgCATNPpJ/vdwEkBrU7GlHFh/tGrkMk+bTaBJtPlRXUApEuIDJCGQM/EMnbsD08+93tDccjCqORqseU2G9wmtGYs4gGOsy4c94e0WmH1wB+uWW+YZwZTFX3dw1RfOHB1rtW3LCxDL2S2h6aAqHD8SLGoyv81XQrbbfKferixSrTtsa1JdT6hfdC3Cl9Sqg8J12lJYuJqumXsK+W5KVHtJIL6uudCoi/oJij21ijJ28OjSnIwY3nfaHysGEaG8gpxQCKWioAJ7L5eRd4VCsNj4RVbVdfhIBSoiuvlw+EIUkN0sZA3NBz0EJNJ5F3izC/QI5ngj3EkEKoEPyw1jD5zfPmz0QjNn1fsEWF4+ScHRmA+OR/8G5Ei8Br3wycy9b6V5EV89qKW1VBAkyboQswRluA+xUvbixeW7HOKd4Spgts3/W+J2Cg6jCE+mpTK4KOaAPSxvwNdCMpQ+hbMky9OuFRNyN9SIRzP4zXfZA4zJ4OFnXGiCF8abXg/ey3941gYgZ+yHfBR+qh5FOqCTisgrjCfqk3w7iXOJAoFufvY5nh3q4BDTRhXZL+8+NOO32eZgYPwwq9X3hxWhzam+Q6SO7qQddbexVK5YgskAVVGlMuS5MNbYgSobn1iGb0by3mvz1gdwxBBqpBQGuU2/eFjHn1Y31SUnf/qrtvEWkx/KWzfozIw2DoQ8tC7rWUnklLtpe1b2hkdO30WpZmWG3jX7O96xQ+AT1L+aa3Vl5bjFiKCJw==
    username: AgCc5577bvx79Tw4R1uQbBo1WoomBgP3JkrkiC2I/JZwjZHSrTxGjtuOv+3I4f9LUuEgPTBGos7dfj6CegP/IJ7H/BnPLdyr8otoqxXM4mbC0jc8GXjRG3QBwqhnlOaFav0jXAshgnRtLFj2MjBO1ltNo0Sz9AQ62YXFS2Qm/50UuOqlSWL5X58ooOZv6WT6T58zw3hIgRkcbdqj6Mo63ee7JUeixOMrhlmgOITIKpWghak5Yq1GmPfIsJ9Xp/OPtgxrYDHqnmcip2mPkUvDGrMawFwUOba59qPxla30doJJK7S3xoPCYrRQ+RfYH5NfnWGbsLTwuXepsL42ewi6JQreaCsf+N+Z1WPKhmjDUcdztOOP+FQ6ixq0raOWT5IHLPL4CLD8eziJYJIJ5yZCgxEKBFvKq17N4CbfgzM+PEO+PGEqakIJMCcUbYppne49MYbbKYu/mzC8n5OWNInghL52+SUFPr/uWSXRRs+wOVp1WRCR+QdnmH02eGEIxdI0JqjmOw3BxMFcrx58PJtqsCiQqscWD6gZLM6zpspqK5Yl+3U0lzaoTL6XNdVIvHMub1sB1/1VbJNTeakrHoZFk8R7XZwvW4KjThseTo02/M9LWOJh+HA1NFJA40z+7Yp29DtrKbmA06BV6QsId42U3n7FDa/YqEqsNX0qUYux0nnjczCmgtYgIUnnsfwZrlgXTp0DrqL6
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
    type: Opaque
