apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    password: AgALfMRcqwRye7j4ifoR84NSI9lAGjdwLt3vWxLO4EKH1ESjOS/ddqPd006CtV0LM1dDFbC7RUhYF9xf3PkiNO7xQFiA8k2I8XIQx7dlUZ2Y1NGs1T+LQ2wodtAMaGLdcYw/9fL6MV8cg8O7HBg15Km0Zsl43fnfJwUbWGrqrmexo4T1eKKtPebhQieYS1CfOdRDu+sT2v4In9ZSrLWRCY5pbOBI5D+7OMmHretuzKKVTDZvcD63nw2/PKjsGMc+N2xbDjPHgJbkpLBD3hr6nxPq7DSc6ZGJZgNuf6JmLlkNsJb/ZlovrSFuEez3X82a7YfxCn/lLWJTyJCQIVD9iu0F6TVT2MTE3l/xJfn8ba92F1xZh8B0WY7m9ylPNVRkgjdqCIjjIbfg1kH3mNd2VsSgfQvZWq3egstl49Vox/F1t9r6/oa5clNG6mJck7XkwnprE/Sm/yTT4wC0z0nUDVkJYF4PukjcW6j3hIqEJnxWW29uNU6Qs615J0r39C9yxlpsgz2YV3Hw20V/C6eHmNGpbP20HEOLUSnsj6r4l+16u5Szw500zcZUV1qC2eOhUZuV6j23YbqSOUZyzozyYs6hO6uOBw7G01jKs8gs/r6LSIyWsnBJvuYEuPDOotVpYpIvjPmY6dUlhVVtXKpnE+vXp1AzhFQ9VWZ1sNAej+Ae0s+lLUYujkfeo4NyKiFu7yWb3LPcyoUYdXf6vW7ToColqb666ulf7Q9fDa1kZmedDg==
    username: AgAaJxTLd4yTts3ENcsY7yWCmEUPjLdPhrTxbFruKRZXVkEIUTlnvKqNTb91BXRSeRNfrxHa1AzVxRBPYhMERaJJuCmb5iE9jDv3dzFX3tO1pKiPy5dwujLmEoy3h8H85RYqzPQJH1SS4KE8H8pD5YHj17W+mf3AmWKcdo1PWVRIM6W+dO931bW9Y4V3uGe9/5gMZyYHzW3ixpcSJ5PRjgaEEYBK7O0WSriwLeRrpQo/pSu6oYsq8Hoh2D0hpCNfvbCkopWJx0Jn1MRiCUfqoV8q+0XMsb2sm2L5M3EME+g3n+LCfLg75UtrpK2JMnvqp8oVmDRq/3NSogyIQI0wV5EGMtx5GWq0XCg5+ZPmZex814Av5P0LGoqgg/sXcyg/O2k5p1w/Jht9GGOdV9g20hFAsO2TEhMRD/d43PGIGi4c+KbPbtcNL+QsH7QbQhJjdoLdz/dekiL9KxBPaeghyH/KR7HdqLofjllh0fona0jp5kHx40zN9zmE04FEu8EhX6TypAcHh67ZhZ+Mjxhy0aU0FhMefPfwO72S+D4YAG5kQvCZyC0eOo0VyZH+cZ579FyC1Adi43OrfRVjy2lZizhurl9XxnflkBnCh6I0UayepN01cgDZ7piepRIo/5rEkayOt1/+z70UYex8iwP//yb4fHb2iA90tTBMhgjJzhiduIQ01jj2sax5Swp112+h2nbkx3ZS
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
    type: Opaque
