apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otomadb-api
spec:
  project: prod-otomadb
  source:
    repoURL: https://github.com/otomad-database/k8s-manifests
    targetRevision: main
    path: api/overlays/prod
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-otomadb
